export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED'
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED'

export const ERROR = 'ERROR'

export const SNACKBAR_ERROR = 'SNACKBAR_ERROR'
export const SNACKBAR_TRANSACTION_RECEIPT = 'SNACKBAR_TRANSACTION_RECEIPT'
export const SNACKBAR_TRANSACTION_CONFIRMED = 'SNACKBAR_TRANSACTION_CONFIRMED'
export const SNACKBAR_MESSAGE = 'SNACKBAR_MESSAGE'

export const GET_BALANCES_PERPETUAL = 'GET_BALANCES_PERPETUAL'
export const BALANCES_PERPETUAL_RETURNED = 'BALANCES_PERPETUAL_RETURNED'

export const GET_BALANCES = 'GET_BALANCES'
export const BALANCES_RETURNED = 'BALANCES_RETURNED'

export const DEPOSIT_LP = 'DEPOSIT_LP'
export const DEPOSIT_LP_RETURNED = 'DEPOSIT_LP_RETURNED'

export const DEPOSIT_ALL_LP = 'DEPOSIT_ALL_LP'
export const DEPOSIT_ALL_LP_RETURNED = 'DEPOSIT_ALL_LP_RETURNED'

export const WITHDRAW_LP = 'WITHDRAW_LP'
export const WITHDRAW_LP_RETURNED = 'WITHDRAW_LP_RETURNED'

export const WITHDRAW_ALL_LP = 'WITHDRAW_ALL_LP'
export const WITHDRAW_ALL_LP_RETURNED = 'WITHDRAW_ALL_LP_RETURNED'
