export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED'
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED'

export const ERROR = 'ERROR'

export const SNACKBAR_ERROR = 'SNACKBAR_ERROR'
export const SNACKBAR_TRANSACTION_RECEIPT = 'SNACKBAR_TRANSACTION_RECEIPT'
export const SNACKBAR_TRANSACTION_CONFIRMED = 'SNACKBAR_TRANSACTION_CONFIRMED'
export const SNACKBAR_MESSAGE = 'SNACKBAR_MESSAGE'

export const GET_ACCOUNT_BALANCES = 'GET_ACCOUNT_BALANCES'
export const ACCOUNT_BALANCES_RETURNED = 'ACCOUNT_BALANCES_RETURNED'

export const GET_CONTRACT_BALANCES = 'GET_CONTRACT_BALANCES'
export const CONTRACT_BALANCES_RETURNED = 'CONTRACT_BALANCES_RETURNED'

export const GET_QUOTE = 'GET_QUOTE'
export const QUOTE_RETURNED = 'QUOTE_RETURNED'

export const APPLY = 'APPLY'
export const APPLY_RETURNED = 'APPLY_RETURNED'

export const GET_COVER = 'GET_COVER'
export const COVER_RETURNED = 'COVER_RETURNED'

export const CLAIM = 'CLAIM'
export const CLAIM_RETURNED = 'CLAIM_RETURNED'

export const REDEEM = 'REDEEM'
export const REDEEM_RETURNED = 'REDEEM_RETURNED'

export const SWAP = 'SWAP'
export const SWAP_RETURNED = 'SWAP_RETURNED'
